# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-27 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
