# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-08 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_page'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
